CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  default_cost BIGINT NOT NULL DEFAULT 0 CHECK (default_cost >= 0),
  default_price BIGINT NOT NULL DEFAULT 0 CHECK (default_price >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX idx_products_name_ci ON products (LOWER(name));

CREATE TABLE movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL CHECK (kind IN ('receipt', 'sale', 'return')),
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  sale_id BIGINT,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_cost BIGINT NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  unit_price BIGINT NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
  store TEXT NOT NULL DEFAULT '',
  occurred_on DATE NOT NULL,
  note TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_movements_product ON movements (product_id);
CREATE INDEX idx_movements_date ON movements (occurred_on);
CREATE INDEX idx_movements_sale ON movements (sale_id);
